services:
  geoapi:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    # links:
    #   - dnmonster

  mongo:
    image: mongo
    
  # dnmonster:
  #   image: amouat/dnmonster:1.0 

  # redis:
  #   image: redis:3.0