services:
  geoapi:
    build: .
    ports:
      - "5000:5000"
      - "9090:9090"
      - "9191:9191"
    environment:
      ENV: DEV
    env_file:
      - key.env
    volumes:
      - ./app:/app
    links:
      - mongo

  mongo:
    image: mongo
